package com.visualmerge.service;

import com.visualmerge.config.WorkspaceProperties;
import com.visualmerge.git.GitOperationException;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Comparator;
import java.util.Locale;
import java.util.UUID;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Owns the temporary filesystem that repositories are cloned into.
 *
 * <p>Every session gets its own directory:
 * <pre>
 *   &lt;root&gt;/session-&lt;uuid&gt;/repository
 * </pre>
 *
 * <p>Nothing outside {@code root} is ever created, read or deleted. Every path
 * handed back is verified to be inside the root before use, so a malformed
 * session id cannot escape the workspace.
 */
@Service
public class WorkspaceService {

    private static final Logger log = LoggerFactory.getLogger(WorkspaceService.class);

    /** Session ids are generated by us, but validated anyway before touching disk. */
    private static final Pattern SESSION_ID = Pattern.compile("session-[a-f0-9]{8,32}");

    private static final String REPOSITORY_DIR = "repository";

    private final Path root;
    private final WorkspaceProperties properties;

    public WorkspaceService(WorkspaceProperties properties) throws IOException {
        this.properties = properties;
        String configured = properties.getRoot();
        if (configured == null || configured.isBlank()) {
            configured = System.getProperty("java.io.tmpdir") + "/visualmerge-workspaces";
        }
        this.root = Path.of(configured).toAbsolutePath().normalize();
        Files.createDirectories(this.root);
        log.info("Workspace root ready ({} session directories will be created here)", this.root);
    }

    /** Creates a fresh, empty session directory and returns its id. */
    public String createSession() {
        String sessionId = "session-" + UUID.randomUUID().toString().replace("-", "").substring(0, 16);
        try {
            Files.createDirectories(repositoryPath(sessionId));
            return sessionId;
        } catch (IOException e) {
            throw new GitOperationException(
                    GitOperationException.Code.WORKSPACE_ERROR,
                    "Could not prepare a workspace for this repository.", e);
        }
    }

    /** The directory a session's repository is cloned into. */
    public Path repositoryPath(String sessionId) {
        return sessionPath(sessionId).resolve(REPOSITORY_DIR);
    }

    /** The session's own directory, guaranteed to live under the workspace root. */
    public Path sessionPath(String sessionId) {
        if (sessionId == null || !SESSION_ID.matcher(sessionId).matches()) {
            throw new GitOperationException(
                    GitOperationException.Code.WORKSPACE_ERROR, "Invalid workspace session.");
        }
        Path resolved = root.resolve(sessionId).normalize();
        if (!resolved.startsWith(root)) {
            // Defence in depth: the pattern above already makes this unreachable.
            throw new GitOperationException(
                    GitOperationException.Code.WORKSPACE_ERROR, "Invalid workspace session.");
        }
        return resolved;
    }

    /** Size of a session's contents in kilobytes, used to enforce the size cap. */
    public long sizeKb(String sessionId) {
        Path path = sessionPath(sessionId);
        if (!Files.exists(path)) {
            return 0;
        }
        try (Stream<Path> files = Files.walk(path)) {
            long bytes = files.filter(Files::isRegularFile).mapToLong(file -> {
                try {
                    return Files.size(file);
                } catch (IOException e) {
                    return 0L;
                }
            }).sum();
            return bytes / 1024;
        } catch (IOException e) {
            log.warn("Could not measure workspace size for {}", sessionId);
            return 0;
        }
    }

    public long maxSizeKb() {
        return (long) properties.getMaxRepositorySizeMb() * 1024;
    }

    /**
     * Deletes a session directory and everything in it. Only ever touches paths
     * under the workspace root; the user's own repositories are never involved.
     */
    public void deleteSession(String sessionId) {
        Path path;
        try {
            path = sessionPath(sessionId);
        } catch (GitOperationException e) {
            return;
        }
        deleteRecursively(path);
    }

    /** Removes session directories older than the configured TTL. */
    public int cleanupStaleSessions() {
        long ttlMillis = (long) properties.getSessionTtlMinutes() * 60_000L;
        if (ttlMillis <= 0) {
            return 0;
        }
        long cutoff = System.currentTimeMillis() - ttlMillis;
        int removed = 0;
        try (Stream<Path> sessions = Files.list(root)) {
            for (Path session : sessions.toList()) {
                String name = session.getFileName().toString().toLowerCase(Locale.ROOT);
                if (!SESSION_ID.matcher(name).matches()) {
                    continue;
                }
                if (Files.getLastModifiedTime(session).toMillis() < cutoff) {
                    deleteRecursively(session);
                    removed++;
                }
            }
        } catch (IOException e) {
            log.warn("Stale workspace sweep failed: {}", e.getMessage());
        }
        if (removed > 0) {
            log.info("Removed {} stale workspace session(s)", removed);
        }
        return removed;
    }

    private void deleteRecursively(Path path) {
        if (!Files.exists(path)) {
            return;
        }
        try {
            // Git packs are read-only on Windows; clear the flag before deleting.
            Files.walkFileTree(path, new SimpleFileVisitor<>() {
                @Override
                public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                    file.toFile().setWritable(true);
                    return FileVisitResult.CONTINUE;
                }
            });
            try (Stream<Path> entries = Files.walk(path)) {
                entries.sorted(Comparator.reverseOrder()).forEach(entry -> {
                    try {
                        Files.deleteIfExists(entry);
                    } catch (IOException e) {
                        log.debug("Could not delete {}", entry.getFileName());
                    }
                });
            }
        } catch (IOException e) {
            log.warn("Workspace cleanup incomplete for {}: {}", path.getFileName(), e.getMessage());
        }
    }

    @PreDestroy
    void shutdown() {
        if (!properties.isCleanupOnShutdown()) {
            return;
        }
        try (Stream<Path> sessions = Files.list(root)) {
            sessions.filter(path -> SESSION_ID.matcher(path.getFileName().toString()).matches())
                    .forEach(this::deleteRecursively);
            log.info("Workspace sessions cleaned up on shutdown");
        } catch (IOException e) {
            log.warn("Shutdown workspace cleanup failed: {}", e.getMessage());
        }
    }
}
